### ISSUE TITLE
react-native-vector-icons dependency is out of date

### ISSUE THREAD

**Issue by cbartondock** [vonovak/react-native-round-checkbox#1]
This module depends on react-native-vector-icons@^3.0.0, which unfortunately is broken in react native > 0.40 (see https://github.com/oblador/react-native-vector-icons/releases/tag/v4.0.0).

For those of us using newer versions of react native and therefore newer versions of react-native-vector-icons, this module gives an "UNMET DEPENDENCY react-native-vector-icons@^3.0.0" error.

As far as I can tell, there aren't other breaking changes in react-native-vector-icons so all that should be necessary is changing package.json

**Comment by cbartondock** [comment]
Submitted a pull request https://github.com/vonovak/react-native-round-checkbox/pull/2

**Comment by vonovak** [comment]
merged and released in 0.3.2
