### ISSUE TITLE
Animation support

### ISSUE THREAD

**Issue by RodolfoGS** [vonovak/react-native-round-checkbox#4]
Hi, great job! Would you consider add animation support? Like the native component in iOS.

For Example:
Go to Settings app -> _Any app_ -> Notifications -> Checkbox

When you tap the native component it make a cool animation.
I think that it could be a good improve to the component.

![ezgif-2-eaf723b81f55](https://user-images.githubusercontent.com/870365/61268787-6f1ef480-a751-11e9-89b3-3860a556d918.gif)

**Comment by vonovak** [comment]
hi! I'm not currently using this but if you provide a PR for this, I'd merge it, thanks.

**Comment by crutchcorn** [comment]
I'll be working on this issue tonight
